sonar.projectKey=Althalas_Backend_BusinessCase
sonar.organization=althalas
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=src/**/*.spec.ts,src/**/*.test.ts,src/main.ts,src/prisma/**
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.ts,src/app.module.ts,src/prisma/**,src/**/*.module.ts,src/**/*.dto.ts,src/**/*.entity.ts
